### ISSUE TITLE
#screeshot issue

### ISSUE THREAD

**Issue by HithaishiDesai** [VarunS2002/Xposed-Disable-FLAG_SECURE#15]
Unable to take screenshot or screen record in AIRTEL XTREAM APP

**Comment by ChaliceChore** [comment]
Not working with Hotstar and Netflix.

**Comment by HithaishiDesai** [comment]
> Not working with Hotstar and Netflix.

Yeah I know.... 


Dear Dev, Kindly fix this issue

**Comment by VarunS2002** [comment]
@HithaishiDesai @iamMG 
Sorry for the late reply.
Have you tried following the instructions given [here](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE#additional-information-on-drm-encrypted-content)?

**Comment by VarunS2002** [comment]
> @HithaishiDesai @iamMG Sorry for the late reply. Have you tried following the instructions given [here](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE#additional-information-on-drm-encrypted-content)?

@HithaishiDesai @iamMG 
I tested this solution myself and it seems to be working for Netflix, therefore it is most likely the case that you missed this so I am closing this issue.
If the issue persists then please reopen this issue and provide more details such as the error message and logs.

**Comment by ChaliceChore** [comment]
I tried liboemcrypto disabler. Still not working. 
Check this out: http://imgur.com/a/spXdrMi

**Comment by VarunS2002** [comment]
> I tried liboemcrypto disabler. Still not working. Check this out: http://imgur.com/a/spXdrMi

Based on the screenshot you provided, the magisk module liboemcrypto disabler is not working. You can tell this since you were allowed to take the screenshot (which includes the playback controls). The fact that the video is black is dealt with by the magisk module since it deals with video stream encryption. Therefore, I cannot do anything about this. However, since it worked for me, I suggest reinstalling Netflix and trying again.
